//! Context compression — summarization of older messages to fit within the model's context window.
//!
//! Corresponds to Python AgentScope's `_compress_memory_if_needed()` and
//! `_split_context_for_compression()` methods on `Agent`.
//!
//! **Note:** Compression is not yet wired into `react_loop.rs`. When integrated,
//! `compress_context` will be called between reasoning iterations when the token
//! count exceeds `context_size * trigger_ratio`. See Python's `_react_agent.py`
//! for the reference implementation.

use std::collections::HashSet;
use std::sync::Arc;

use agent_scope_message::{ContentBlock, Msg};
use agent_scope_model::ChatModel;
use agent_scope_state::{AgentState, SummaryContent};

use crate::agent_error::AgentError;
use crate::config::ContextConfig;

/// Compress older messages in the agent's state context.
///
/// When the estimated token count exceeds `context_size * trigger_ratio`,
/// the oldest messages are replaced with a summary generated by the model.
///
/// Corresponds to Python AgentScope's `_compress_memory_if_needed()`.
/// Wired into `react_loop.rs` between reasoning iterations.
pub(crate) async fn compress_context(
    model: &Arc<dyn ChatModel>,
    state: &std::sync::RwLock<AgentState>,
    config: &ContextConfig,
    _session_id: &str,
    // Pre-computed by the caller from the message list that will actually be
    // sent (context + system prompt + tool schemas). Passed in rather than
    // recomputed here so the trigger decision matches the caller's (a recount
    // with a different shape could disagree and silently skip compression).
    token_count: usize,
) -> Result<(), AgentError> {
    let context_size = model.context_size();

    // Snapshot the context length WITHOUT holding the write lock: `count_tokens`
    // is a user-implemented trait method that could panic, and panicking while
    // the `RwLock` is held would poison it, breaking every later state access
    // in the agent (audit A5).
    let context_len = {
        let state_read = state.read().unwrap_or_else(|e| e.into_inner());
        state_read.context.len()
    };

    let trigger_threshold = (context_size as f64 * config.trigger_ratio) as usize;

    if token_count <= trigger_threshold {
        return Ok(()); // No compression needed
    }

    // Calculate how many tokens to reserve for new messages
    let reserve_threshold = (context_size as f64 * config.reserve_ratio) as usize;
    let target_reduction = token_count.saturating_sub(reserve_threshold);

    // Simple strategy: remove oldest messages until estimated tokens fit
    // More sophisticated strategies (model-based summarization) deferred
    let mut removed_tokens = 0usize;
    let mut split_idx = 0usize;

    // roughly: each message ~ avg token count
    let msg_tokens = token_count / context_len.max(1);
    for i in 0..context_len {
        if removed_tokens + msg_tokens > target_reduction {
            break;
        }
        removed_tokens += msg_tokens;
        split_idx = i + 1;
    }

    if split_idx == 0 {
        return Ok(()); // Nothing to compress
    }

    // Tool-pair-aware boundary (round-4 H10). Each tool round is stored as an
    // `assistant(ToolCall)` message immediately followed by one
    // `assistant(ToolResult)` message per call. If `drain(0..split_idx)` keeps
    // a ToolResult whose ToolCall was drained, the next model call would carry
    // an orphan tool result and be rejected by the API. Extend the boundary so
    // every result whose call was drained is drained too.
    let split_idx = {
        let state_read = state.read().unwrap_or_else(|e| e.into_inner());
        let context = &state_read.context;
        let drained_call_ids: HashSet<String> = context[0..split_idx]
            .iter()
            .flat_map(|m| m.content.iter())
            .filter_map(|b| match b {
                ContentBlock::ToolCall(tc) => Some(tc.id.clone()),
                _ => None,
            })
            .collect();
        let mut adjusted = split_idx;
        while let Some(msg) = context.get(adjusted) {
            let is_orphan_result = msg.content.iter().any(|b| match b {
                ContentBlock::ToolResult(tr) => drained_call_ids.contains(&tr.id),
                _ => false,
            });
            if !is_orphan_result {
                break;
            }
            adjusted += 1;
        }
        adjusted
    };

    let mut state_write = state.write().unwrap_or_else(|e| e.into_inner());
    // Clamp the drain boundary to the actual context length. `split_idx` is
    // derived from a read snapshot taken just above; under future concurrent
    // mutation `split_idx` could exceed the current length, and `drain(0..n)`
    // with `n > len` panics *while holding the write lock*, poisoning the
    // RwLock for every later state access (round-4 H10 follow-up).
    let drain_to = split_idx.min(state_write.context.len());
    // Extract compressed messages and summarize
    let _old_messages: Vec<Msg> = state_write.context.drain(0..drain_to).collect();

    // For now: set summary to a placeholder text
    // Full model-based summarization is deferred to a future iteration
    let summary_text = format!(
        "[Compressed {} messages, ~{} tokens]",
        drain_to, removed_tokens
    );
    state_write.summary = SummaryContent::Text(summary_text.clone());

    // Surface the summary to the model. Previously it was stored on the state
    // but never included in the call messages, so the agent silently "forgot"
    // the compressed turns without any recap (round-4 M11).
    if let Ok(summary_msg) = agent_scope_message::factory::user_msg("", &summary_text) {
        state_write.context.insert(0, summary_msg);
    }

    tracing::info!(
        compressed_messages = drain_to,
        remaining = state_write.context.len(),
        "Context compressed"
    );

    Ok(())
}

/// Fallback truncation: keep last N messages fitting within reserve_ratio.
///
/// Corresponds to Python AgentScope's context truncation path.
/// Used as fallback inside `compress_context` when token-count-based compression
/// cannot reduce context enough.
pub(crate) fn truncate_context(
    state: &mut AgentState,
    _config: &ContextConfig,
    max_messages: usize,
) {
    if state.context.len() > max_messages {
        let remove_count = state.context.len() - max_messages;
        state.context.drain(0..remove_count);
        state.summary =
            SummaryContent::Text(format!("[Truncated {} oldest messages]", remove_count));
    }
}
