//! Context compression — summarization of older messages to fit within the model's context window.
//!
//! Corresponds to Python AgentScope's `_compress_memory_if_needed()` and
//! `_split_context_for_compression()` methods on `Agent`.
//!
//! **Note:** Compression is not yet wired into `react_loop.rs`. When integrated,
//! `compress_context` will be called between reasoning iterations when the token
//! count exceeds `context_size * trigger_ratio`. See Python's `_react_agent.py`
//! for the reference implementation.

use std::sync::Arc;

use agent_scope_message::Msg;
use agent_scope_model::ChatModel;
use agent_scope_state::{AgentState, SummaryContent};

use crate::agent_error::AgentError;
use crate::config::ContextConfig;

/// Compress older messages in the agent's state context.
///
/// When the estimated token count exceeds `context_size * trigger_ratio`,
/// the oldest messages are replaced with a summary generated by the model.
///
/// Corresponds to Python AgentScope's `_compress_memory_if_needed()`.
/// Wired into `react_loop.rs` between reasoning iterations.
pub(crate) async fn compress_context(
    model: &Arc<dyn ChatModel>,
    state: &std::sync::RwLock<AgentState>,
    config: &ContextConfig,
    _session_id: &str,
    // Pre-computed by the caller from the message list that will actually be
    // sent (context + system prompt + tool schemas). Passed in rather than
    // recomputed here so the trigger decision matches the caller's (a recount
    // with a different shape could disagree and silently skip compression).
    token_count: usize,
) -> Result<(), AgentError> {
    let context_size = model.context_size();

    // Snapshot the context length WITHOUT holding the write lock: `count_tokens`
    // is a user-implemented trait method that could panic, and panicking while
    // the `RwLock` is held would poison it, breaking every later state access
    // in the agent (audit A5).
    let context_len = {
        let state_read = state.read().unwrap_or_else(|e| e.into_inner());
        state_read.context.len()
    };

    let trigger_threshold = (context_size as f64 * config.trigger_ratio) as usize;

    if token_count <= trigger_threshold {
        return Ok(()); // No compression needed
    }

    // Calculate how many tokens to reserve for new messages
    let reserve_threshold = (context_size as f64 * config.reserve_ratio) as usize;
    let target_reduction = token_count.saturating_sub(reserve_threshold);

    // Simple strategy: remove oldest messages until estimated tokens fit
    // More sophisticated strategies (model-based summarization) deferred
    let mut removed_tokens = 0usize;
    let mut split_idx = 0usize;

    // roughly: each message ~ avg token count
    let msg_tokens = token_count / context_len.max(1);
    for i in 0..context_len {
        if removed_tokens + msg_tokens > target_reduction {
            break;
        }
        removed_tokens += msg_tokens;
        split_idx = i + 1;
    }

    if split_idx == 0 {
        return Ok(()); // Nothing to compress
    }

    let mut state_write = state.write().unwrap_or_else(|e| e.into_inner());
    // Extract compressed messages and summarize
    let _old_messages: Vec<Msg> = state_write.context.drain(0..split_idx).collect();

    // For now: set summary to a placeholder text
    // Full model-based summarization is deferred to a future iteration
    state_write.summary = SummaryContent::Text(format!(
        "[Compressed {} messages, ~{} tokens]",
        split_idx, removed_tokens
    ));

    tracing::info!(
        compressed_messages = split_idx,
        remaining = state_write.context.len(),
        "Context compressed"
    );

    Ok(())
}

/// Fallback truncation: keep last N messages fitting within reserve_ratio.
///
/// Corresponds to Python AgentScope's context truncation path.
/// Used as fallback inside `compress_context` when token-count-based compression
/// cannot reduce context enough.
pub(crate) fn truncate_context(
    state: &mut AgentState,
    _config: &ContextConfig,
    max_messages: usize,
) {
    if state.context.len() > max_messages {
        let remove_count = state.context.len() - max_messages;
        state.context.drain(0..remove_count);
        state.summary =
            SummaryContent::Text(format!("[Truncated {} oldest messages]", remove_count));
    }
}
