//! Context compression — summarization of older messages to fit within the model's context window.
//!
//! Corresponds to Python AgentScope's `_compress_memory_if_needed()` and
//! `_split_context_for_compression()` methods on `Agent`.
//!
//! **Note:** Compression is not yet wired into `react_loop.rs`. When integrated,
//! `compress_context` will be called between reasoning iterations when the token
//! count exceeds `context_size * trigger_ratio`. See Python's `_react_agent.py`
//! for the reference implementation.

use std::sync::Arc;

use agent_scope_message::Msg;
use agent_scope_model::ChatModel;
use agent_scope_state::{AgentState, SummaryContent};

use crate::agent_error::AgentError;
use crate::config::ContextConfig;

/// Compress older messages in the agent's state context.
///
/// When the estimated token count exceeds `context_size * trigger_ratio`,
/// the oldest messages are replaced with a summary generated by the model.
///
/// Corresponds to Python AgentScope's `_compress_memory_if_needed()`.
/// Wired into `react_loop.rs` between reasoning iterations.
pub(crate) async fn compress_context(
    model: &Arc<dyn ChatModel>,
    state: &std::sync::RwLock<AgentState>,
    config: &ContextConfig,
    _session_id: &str,
) -> Result<(), AgentError> {
    let context_size = model.context_size();
    let mut state_write = state.write().unwrap();

    // Estimate current tokens
    let messages = &state_write.context;
    let token_count = model.count_tokens(messages, None);

    let trigger_threshold = (context_size as f64 * config.trigger_ratio) as usize;

    if token_count <= trigger_threshold {
        return Ok(()); // No compression needed
    }

    // Calculate how many tokens to reserve for new messages
    let reserve_threshold = (context_size as f64 * config.reserve_ratio) as usize;
    let target_reduction = token_count.saturating_sub(reserve_threshold);

    // Simple strategy: remove oldest messages until estimated tokens fit
    // More sophisticated strategies (model-based summarization) deferred
    let mut removed_tokens = 0usize;
    let mut split_idx = 0usize;

    for (i, _msg) in messages.iter().enumerate() {
        // roughly: each message ~ avg token count
        let msg_tokens = token_count / messages.len().max(1);
        if removed_tokens + msg_tokens > target_reduction {
            break;
        }
        removed_tokens += msg_tokens;
        split_idx = i + 1;
    }

    if split_idx == 0 {
        return Ok(()); // Nothing to compress
    }

    // Extract compressed messages and summarize
    let _old_messages: Vec<Msg> = state_write.context.drain(0..split_idx).collect();

    // For now: set summary to a placeholder text
    // Full model-based summarization is deferred to a future iteration
    state_write.summary = SummaryContent::Text(format!(
        "[Compressed {} messages, ~{} tokens]",
        split_idx, removed_tokens
    ));

    tracing::info!(
        compressed_messages = split_idx,
        remaining = state_write.context.len(),
        "Context compressed"
    );

    Ok(())
}

/// Fallback truncation: keep last N messages fitting within reserve_ratio.
///
/// Corresponds to Python AgentScope's context truncation path.
/// **TODO:** Wire into `react_loop.rs` as fallback when compression fails.
#[allow(dead_code)]
pub(crate) fn truncate_context(
    state: &mut AgentState,
    _config: &ContextConfig,
    max_messages: usize,
) {
    if state.context.len() > max_messages {
        let remove_count = state.context.len() - max_messages;
        state.context.drain(0..remove_count);
        state.summary =
            SummaryContent::Text(format!("[Truncated {} oldest messages]", remove_count));
    }
}
