[package]
name = "workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "workspace"
path = "src/main.rs"

[dependencies]
agent_scope_workspace = { path = "../../crates/agent_scope_workspace" }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
tempfile.workspace = true
