[package]
name = "memory"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "memory"
path = "src/main.rs"

[dependencies]
agent_scope_memory = { path = "../../crates/agent_scope_memory" }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
tempfile.workspace = true
