[package]
name = "agentscope"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
autoexamples = false

[workspace]
members = [
    "crates/*", "examples/pi-rust",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/ningning0111/agentscope-rust"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
base64 = "0.22"
schemars = "0.8"
clap = { version = "4", features = ["derive", "env"] }
thiserror = "2"
gray_matter = { version = "0.3.2", default-features = false, features = ["yaml"] }
globset = "0.4.20"
walkdir = "2.5.0"

[dependencies]
agent_scope_agent = { path = "crates/agent_scope_agent" }
agent_scope_dashscope = { path = "crates/agent_scope_dashscope" }
agent_scope_tool = { path = "crates/agent_scope_tool" }
agent_scope_message = { path = "crates/agent_scope_message" }
agent_scope_event = { path = "crates/agent_scope_event" }
agent_scope_memory = { path = "crates/agent_scope_memory" }
agent_scope_state = { path = "crates/agent_scope_state" }
agent_scope_rag = { path = "crates/agent_scope_rag" }
agent_scope_embedding = { path = "crates/agent_scope_embedding" }
agent_scope_workspace = { path = "crates/agent_scope_workspace" }
agent_scope_mcp = { path = "crates/agent_scope_mcp" }
agent_scope_sandbox = { path = "crates/agent_scope_sandbox" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
dotenv = "0.15"
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
uuid.workspace = true
