[package]
name = "tool"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "tool"
path = "src/main.rs"

[dependencies]
agent_scope_agent = { path = "../../crates/agent_scope_agent" }
agent_scope_event = { path = "../../crates/agent_scope_event" }
agent_scope_message = { path = "../../crates/agent_scope_message" }
agent_scope_rig = { path = "../../crates/agent_scope_rig" }
agent_scope_tool = { path = "../../crates/agent_scope_tool" }
anyhow.workspace = true
clap.workspace = true
dotenv.workspace = true
futures.workspace = true
schemars.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
